title: dhodgkin.com
tagline: Personal blog of Damien Hodgkin.
description: A personal blog and notes from Damien Hodgkin, covering topics such as software development, programming languages, and technology.
url: "https://dhodgkin.com"
baseurl: ""
lang: en

author:
  name: Damien Hodgkin
  email: dracul01@gmail.com
  github: https://github.com/dhodgkin
  github_org: https://github.com/Purple-Druid
  url: https://dhodgkin.com

permalink: pretty
paginate: 5
paginate_path: "/page:num/"
excerpt_separator: "<!--more-->"

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-fontawesome-svg

feed:
  path: atom.xml

comments:
  enabled: true
  utterances:
    repo: "dhodgkin/dhodgkin.github.io"
    issue_term: "pathname"
    label: "comments"
    theme_light: "github-light"
    theme_dark: "github-dark"

exclude:
  - .rvmrc
  - .rbenv-version
  - .bundle
  - .jekyll-cache
  - .jekyll-metadata
  - .sass-cache
  - node_modules
  - vendor
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
  - changelog.md

production_url: "https://dhodgkin.com"

JB:
  comments:
    provider: false
  analytics:
    provider: false
  sharing:
    provider: false
  categories_path: /categories/
  tags_path: /tags/
  atom_path: /atom.xml
