title: dhodgkin.com
tagline: Just my blog... about... uh... nothing
description: Personal blog and notes from Damien Hodgkin.
url: "https://dhodgkin.com"
baseurl: ""
lang: en

author:
  name: Damien Hodgkin
  email: dracul01@gmail.com
  github: https://github.com/dhodgkin
  url: https://dhodgkin.com

permalink: pretty
paginate: 5
paginate_path: "/page:num/"
excerpt_separator: "<!--more-->"

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

feed:
  path: atom.xml

exclude:
  - .rvmrc
  - .rbenv-version
  - .bundle
  - .jekyll-cache
  - .jekyll-metadata
  - .sass-cache
  - node_modules
  - vendor
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
  - changelog.md

production_url: "https://dhodgkin.com"

JB:
  comments:
    provider: false
  analytics:
    provider: false
  sharing:
    provider: false
  categories_path: /categories/
  tags_path: /tags/
  atom_path: /atom.xml
